Fix collab server formidable (#53)
* 1. Issue fix :"TypeError: r is not a function" shows when run collab server

* FIX: Errors with formidable when bundling collab server.

* FIX: CORS error on image upload

* Fixes:
1. Saving file not happening.
2. Not returning image on GET call.

* Fix for IRAD-901: New collab server reusing base PM collab server to resolve collaboration inconsistencies.

* 1. "saveimage" functionality in Upload image is moved from build_web_server to a separate server.

* FIX: Unable to upload image with  fully qualified Url

* 1. Replaced chanzuckerberg/prosemirror-tables with ProseMirror/prosemirror-tables.
2. Fix : Licit editor tollbar poorly configured.
3. Modified README.md file to include commands to
run image server for upload image.

* New Image Server to deal image upload. Solved CORS issues.

* 1. Licit Editor - Cannot reference image using fully qualified URL
2. Licit Editor - Editor allows changing font sizes when disabled
3. Licit Editor - Horizontal Line button is not greyed out when editor is disabled.

* 1. Run Image server using bundle.
2. Use cors package instead of our own cors handling in image server where express is used.

* Flow type checker in Collab & Image server.

* Do type checking only in development mode.

Co-authored-by: Ashfaq Shamsudeen <ashfaq.shamsudeen@firmusoft.co.in>
Co-authored-by: arathy <arathy.gopal@firmusoft.co.in>
Co-authored-by: seybi.ea <seybi.ea@firmusoft.co.in>